version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vote_buddy
      POSTGRES_PASSWORD: vote_buddy
      POSTGRES_DB: vote_buddy
    ports:
      - "5432:5432"
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
