"""add meeting fields

Revision ID: 4b7aeabb87a7
Revises: 22043ac5e6e1
Create Date: 2025-06-13 14:10:18.689616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7aeabb87a7'
down_revision = '22043ac5e6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('opens_at_stage1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closes_at_stage1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('opens_at_stage2', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closes_at_stage2', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ballot_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('revoting_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('chair_notes_md', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('chair_notes_md')
        batch_op.drop_column('revoting_allowed')
        batch_op.drop_column('ballot_mode')
        batch_op.drop_column('closes_at_stage2')
        batch_op.drop_column('opens_at_stage2')
        batch_op.drop_column('closes_at_stage1')
        batch_op.drop_column('opens_at_stage1')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
