"""add missing indexes and constraints

Revision ID: 96ba2b012319
Revises: ae1c073df94d
Create Date: 2025-06-24 08:23:38.826718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96ba2b012319'
down_revision = 'ae1c073df94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amendment_conflicts_meeting_id'), ['meeting_id'], unique=False)

    with op.batch_alter_table('amendment_versions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('amendments', schema=None) as batch_op:
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_unique_constraint('uq_api_tokens_token_hash', ['token_hash'])

    with op.batch_alter_table('email_settings', schema=None) as batch_op:
        batch_op.alter_column('auto_send',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('motion_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motion_options_motion_id'), ['motion_id'], unique=False)

    with op.batch_alter_table('motion_versions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('motions', schema=None) as batch_op:
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.create_foreign_key('fk_motions_proposer_id_members', 'members', ['proposer_id'], ['id'])
        batch_op.create_foreign_key('fk_motions_seconder_id_members', 'members', ['seconder_id'], ['id'])
        batch_op.drop_column('change_requested')

    with op.batch_alter_table('runoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runoffs_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runoffs_meeting_id'))

    with op.batch_alter_table('motions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_requested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_motions_proposer_id_members', type_='foreignkey')
        batch_op.drop_constraint('fk_motions_seconder_id_members', type_='foreignkey')
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('motion_versions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('motion_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motion_options_motion_id'))

    with op.batch_alter_table('email_settings', schema=None) as batch_op:
        batch_op.alter_column('auto_send',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_api_tokens_token_hash', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('amendments', schema=None) as batch_op:
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('amendment_versions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('amendment_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amendment_conflicts_meeting_id'))

    # ### end Alembic commands ###
